server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/debatehub
    username: debate_user
    password: ${DB_PASSWORD:ChangeMe_Local_Only_123}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: "5glsYXwh7LkYCqHFkE6YPVqUZHBIV26zbrhI4rgXG7jlDaMoqIfYo5lwfAJ2tZvQ"
    expiresInMinutes: 120
